FirstDjangoAppGASP3/mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    #url(r'^polls/', include('polls.urls')),
	url(r'^polls/', include('polls.urls', namespace="polls")),
]

FirstDjangoAppGASP3/polls/urls.py
from django.conf.urls import url

from . import views

print views.index

urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
	url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name="results"),
	url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name="vote"),
	url(r'^(?P<question_id>[0-9]+)/questao/$', views.editar_questao, name="editar_questao"),
	url(r'^questao/$', views.editar_questao, name="nova_questao")
]

FirstDjangoAppGASP3/polls/models.py
from django.db import models
import datetime
from django.utils import timezone

# Create your models here.

class Question(models.Model):
	question_text = models.CharField(max_length=200)
	pub_date = models.DateTimeField('data publicado')

	def __str__(self):
		return self.question_text

	def was_published_recently(self):
		return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
	was_published_recently.admin_order_field = 'pub_date'
	was_published_recently.boolean = True
	was_published_recently.short_description = 'Published recently'
	
class Choice(models.Model):
	question = models.ForeignKey(Question)
	choice_text = models.CharField(max_length=200)
	votes = models.IntegerField(default=0)
	
	def __str__(self):
		return self.choice_text

FirstDjangoAppGASP3/polls/views.py
# Create your views here.
from django.http import HttpResponse
from .models import Question


#def index(request):
#	return HttpResponse("Hello, world. Yo're at the polls index.")

#def index(request):
#	latest_question_list = Question.objects.order_by('-pub_date')[:5]
#
#	output = ','.join([k.question_text for k in latest_question_list])
#	return HttpResponse(output)

#from django.template import RequestContext, loader

#def index(request):
#	latest_question_list = Question.objects.order_by('-pub_date')[:5]
#	template = loader.get_template('polls/index.html')
#	context = RequestContext(request, {
#		'latest_question_list': latest_question_list,
#	})
#	return HttpResponse(template.render(context))

# ## o codigo acima pode ser reescrito utilizando o atalho render()

from django.shortcuts import render

def index(request):
	latest_question_list = Question.objects.order_by('-pub_date')[:5]
	context = {'latest_question_list':latest_question_list}
	return render (request, 'polls/index.html', context) # retorna um HttpResponse



#def detail(request, question_id):
#	return HttpResponse("You're looking at question %s." %question_id)

#from django.http import Http404
#def detail(request, question_id):
#	try:
#		question = Question.objects.get(pk=question_id)
#	except Question.DoesNotExist:
#		raise Http404("Question does not exists")
#
#	return render(request, 'polls/detail.html', {'question':question})
from django.shortcuts import get_object_or_404

def detail(request, question_id):
	question = get_object_or_404(Question, pk=question_id)
	return render(request, 'polls/detail.html', {'question':question})


def results(request, question_id):
	response = "You're looking at the results of question %s."
	return HttpResponse(response %question_id)

def vote(request, question_id):
	return HttpResponse("You're voting on question %s." %question_id)

def editar_questao(request, question_id=''):
	try:
		question = Question.objects.get(pk=question_id)
	except:
		question = ''
	return render(request, 'polls/edit_question.html', {'question':question})

FirstDjangoAppGASP3/polls/templates/polls/detail.html
<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

<script type="text/javascript">

</script>

<div class="container">

<h1>{{ question.question_text }}</h1>

<div class="table-responsive">

<table id="tabela" class="table table-hover table-condensed">
	<thead>
	<tr>
		<td><h4>Escolha</h4></td>
		<td><h4>Votos</h4></td>
	</tr>
	</thead>
	<tbody>
{% for choice in question.choice_set.all %}
		<tr>
			<td>
				{{ choice.choice_text }}
			</td>
			<td>
				{{ choice.votes }}
			</td>
		</tr>

{% endfor %}

	<button type="button" class="btn btn-primary"> Gravar </button>

	</tbody>
</table>

</div>

</div>

FirstDjangoAppGASP3/polls/templates/polls/edit_question.html
Editar question: {{ question }}

FirstDjangoAppGASP3/polls/templates/polls/index.html
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
<!--<script type="text/javascript">
	$(document).ready(function(){
		alert('entrou !');
	});
</script>-->
<div class="container">

<table class="table table-hover table-condensed">

<tr>
	<thead>
		<tr>
			<td><h3>Descricao</h3></td><td><h3>Data Publicacao</h3></td><td><h3>Editar</h3></td>
		</tr>
	</thead>
</tr>
{% if latest_question_list %}
<tbody>

	{% for question in latest_question_list %}
	<tr>
		<td>{{ question }}</td>
		<td>{{ question.pub_date }}</td>
		<td> 
			<!--<a href="/polls/{{ question.id }}/"> Editar </a>-->
			<a href="{% url 'polls:detail' question.id %}">Editar</a>
		</td>

	</tr>
	{% endfor %}

{% else %}
	<tr>
		<td>
		<p>No polls are available. </p>
		</td>
		<td></td>
		<td></td>
	</tr>
{% endif %}

</tbody>

</table>

<button type="button" class="btn btn-default"> Novo </button>

</div>